version: "2.1"
executors:
    node:
        docker:
            - image: node:13-alpine
    node_and_db:
        docker:
            - image: node:13-alpine
              environment:
                  DATABASE_TEST_URL: postgres://postgres:test@localhost:5432/test
                  DATABASE_URL: postgres://postgres:test@localhost:5432/test
                  HASH_SECRET: circleci
            - image: circleci/postgres:alpine
              environment:
                  POSTGRES_USER: postgres
                  POSTGRES_PASSWORD: test
                  POSTGRES_DB: test


commands:
    checkout_and_attach_workspace:
        steps:
            - checkout
            - attach_workspace:
                at: .
            - run: ls -al

jobs:
    install:
        executor: node
        steps:
            - checkout
            - restore_cache:
                keys:
                    - v2-deps-{{ checksum "yarn.lock" }}
                    - v2-deps
            - run: yarn
            - run:
                  working_directory: packages/client
                  command: yarn --frozen-lockfile
            - run:
                  working_directory: packages/server
                  command: yarn --frozen-lockfile
            - save_cache:
                key: v2-deps-{{ checksum "yarn.lock" }}
                paths:
                    - ~/.cache/yarn
                    - node_modules
                    - packages/client/node_modules/
                    - packages/server/node_modules/
            - persist_to_workspace:
                  root: .
                  paths:
                      - node_modules
                      - packages/client/node_modules/
                      - packages/server/node_modules/
    test_client:
        executor: node
        steps:
            - checkout_and_attach_workspace
            - run:
                working_directory: ~/project/packages/client
                name: test
                command: yarn test:unit
    test_server:
        executor: node_and_db
        steps:
            - checkout_and_attach_workspace
            - run:
                working_directory: ~/project/packages/server
                name: test
                command: yarn test:cov
            - store_test_results:
                path: ./server/coverage
    build_client:
        executor: node
        steps:
            - checkout_and_attach_workspace
            - run:
                working_directory: ~/project/packages/client
                name: build
                command: yarn build
    build_server:
        executor: node
        steps:
            - checkout_and_attach_workspace
            - run:
                working_directory: ~/project/packages/server
                name: build
                command: yarn build

workflows:
    main:
        jobs:
            - install
            - test_client:
                  requires:
                      - install
            - test_server:
                  requires:
                      - install
            - build_client:
                  requires:
                      - install
            - build_server:
                  requires:
                      - install
